### ISSUE TITLE
Open Graph Tags not rendered correctly

### ISSUE THREAD

**Issue by tomsonnemans** [ralphjsmit/laravel-seo#12]
It seems the default Open Graph tags aren't rendered as should be.

Currently it renders the tag `<meta name="og:title" content="Title">`, but it should be `<meta name="title" property="og:title" content="Title">`

So in the OpenGrapTag class, it should not adjust the value of the name, but add property with the value og:[name value].

Title in this case is just an example. It has to be adjusted for all Open Graph tags.

**Comment by ralphjsmit** [comment]
Hmm, on first glance that looks like a good point of you. I'll investigate and update it later this week, since I don't have time today or tomorrow. Thanks!

**Comment by ralphjsmit** [comment]
Thanks for reporting! This is fixed in 1.0.2. 👍

**Comment by tomsonnemans** [comment]
Thanks for responding and solving it so fast.
