### ISSUE TITLE
How to use absolute path to images in seo?

### ISSUE THREAD

**Issue by rushi7997** [ralphjsmit/laravel-seo#14]
Hello, we are using Vapor to host our application, and it does not use the relative path to the public folder instead, it uses an absolute path which we can get using `asset()` helper inside the application.

How can I use the absolute path for the images of the products.?

**Comment by ralphjsmit** [comment]
I've no personal experience with Vapor, but is this the default in Vapor to use the `asset()` helper instead of the `public_path()`?

Perhaps we could switch `public_path()` with `asset()`, but I'm not 100% sure if that would have complications..

**Comment by ralphjsmit** [comment]
Awesome!
