### ISSUE TITLE
How to fill seo information on pages without model

### ISSUE THREAD

**Issue by Blinks44** [ralphjsmit/laravel-seo#15]
Greetings! Thank you for your job, i have one question:

For example i have Contact page with PagesController@contact method associated with it (it's just returns a view), how can i set own title, description etc. in contact controller method, without model?

**Comment by ralphjsmit** [comment]
Hey Sergey, 

Thanks for your message!

If I understand you correctly, you should be able to do something like this, right before outputting your view:
```php
// In your controller, right before showing the view:
SEOManager::SEODataTransformer(function (SEOData $SEOData): SEOData {
   $SEOData->title = 'Transformed Title';
   // $SEOData->description = '';
   // $SEOData->author = '';
   // More properties available...

   return $SEOData;
});
```

I agree with you that this probably isn’t that obvious, so perhaps I’ll make this a little bit ’nicer’ in the future.

Let me know if that works!

**Comment by Blinks44** [comment]
Yep, it works, thx! Not super elegant, but works)
Just for clarity: can we add automatic suffix support for code above, or for now hardcode suffix in ```$SEOData->title```?

**Comment by ralphjsmit** [comment]
Awesome! Automatic suffix doesn't work, but you could do it like this:

```php
SEOManager::SEODataTransformer(function (SEOData $SEOData): SEOData {
   $SEOData->title = 'Transformed Title' . config('seo.title.suffix');

   return $SEOData;
});
```

**Comment by Blinks44** [comment]
Thank you! Everything works now
