### ISSUE TITLE
laravel-seo for static pages (without model)

### ISSUE THREAD

**Issue by camya** [ralphjsmit/laravel-seo#16]
Often I create static pages **without any model** attached. (See example controller below)

**Feature request:** It would be great, if I just can fill the plain SEOData() object and pass this object to the layout template.

```
class Homepage extends Controller
{
    public function index()
    {
        return view('project.frontend.page.homepage.index', [
            'seoData' => new SEOData(
                title: 'Awesome News - My Project',
                description: 'Lorem Ipsum',
            ),
        ]);
    }
}
```

The $seoData set in the controller is than passed to the layout file and outputted with seo($seoData).

```
{!! seo($seoData) !!}
```

**Comment by ralphjsmit** [comment]
Thanks for the idea, definitely a good one. Implementing it wasn't difficult, so I just released a new version with it. 💪 See the [new docs](https://github.com/ralphjsmit/laravel-seo/tree/1.1.0#passing-seodata-directly-from-the-controller) here.

**Comment by camya** [comment]
Just tested it. Works fine for me! Great work. 👍
