### ISSUE TITLE
robots -  Allow to set values like "noindex" (in RobotsTags)

### ISSUE THREAD

**Issue by camya** [ralphjsmit/laravel-seo#17]
I try to set `<meta name="robots" content="noindex">` for a Terms & Condition page, but this is not possible.

This is how I think it should work... 

```
$SEOData = new SEOData(
    title: 'Terms & Services',
    description: 'These are our T&C.',
    robots => 'noindex',
);
```

At the moment, the method `RobotsTags::initialize()` just pushes the string 'max-snippet:-1,max-image-preview:large,max-video-preview:-1' every time.

**Comment by ralphjsmit** [comment]
Currently the SEOData object doesn't support the robots tag. Perhaps in the future, but not yet at least. 

You might want to PR it if you have time, it's a relatively simple change.

**Comment by camya** [comment]
[PR Robots Tag feature](https://github.com/ralphjsmit/laravel-seo/pull/19)
