### ISSUE TITLE
mutateFormDataBeforeSave for SEO Plugin

### ISSUE THREAD

**Issue by falconsmilie** [ralphjsmit/laravel-seo#24]
Hi. Thanks for the great plugin.

I started looking at it today and am wondering how I can manipulate the SEO data from the Filament form before it is being saved. The SEO data does not appear in the `$data` array which is passed to Filament's `mutateFormDataBeforeSave` method.

I'm wondering if there is a feature where I can set SEO data before being saved to the database (without the user entering data in the form). If I could do this, i could check for null form values in the SEO form fields and then save the SEO data (populated from the model and/or $data values). I still need to give users the option to enter data into the SEO form fields.

I saw the method you have provided `getDynamicSEOData` and i could use that, but for my use case it will require querying the database for the seo row of the model, checking it for null values, and then returning that. It would be nice if I didn't have to go to that much effort :)

**Comment by ralphjsmit** [comment]
Hey @falconsmilie, did you already find the solution or isn't it relevant anymore?
