### ISSUE TITLE
Class "App\Http\Controllers\SEOData" not found

### ISSUE THREAD

**Issue by salmanmichsan** [ralphjsmit/laravel-seo#31]
in my controller :
$seo = new SEOData(

            title: $room->title,

            description: $room->description,

        );

        // return $seo;

        return view('web.pages.roomdetail',compact('room','ruangan','offers','seo'));

**Comment by poonasor** [comment]
having the same issue here in my controller

**Comment by ralphjsmit** [comment]
@poonasor You need to import it:
```php
use RalphJSmit\Laravel\SEO\Support\SEOData;
```

**Comment by poonasor** [comment]
Thanks @ralphjsmit I've tired that before but still getting
`Undefined variable $SEOData`

**Comment by poonasor** [comment]
@ralphjsmit that wasn't my code, heres what I have

`Route::get('/test', function () {
    return view('test', [
        'SEOData' => new SEOData(
            title: 'Awesome News - My Project',
            description: 'Lorem Ipsum',
        ),
    ]);
});`

appreciate it

**Comment by ralphjsmit** [comment]
@poonasor Ok, what's your Blade code?

**Comment by poonasor** [comment]
in my layout.blade.php in views/components is

{!! seo($SEOData) !!}

**Comment by poonasor** [comment]
So for the $SEOData to work in /views/components/layout.blade.php

I needed to add in AppServiceProvider.php in the boot() function
```
        // Share the SEOData variable with all views
        View::share('SEOData', new SEOData(
            title: 'Awesome News - My Project',
            description: 'Lorem Ipsum',
        ));
```

however, the title and description is the same for all pages..

**Comment by ralphjsmit** [comment]
@poonasor How does your `test.blade.php` look like? You need to pass the $SEOData variable from the `test.blade.php` file into your `layout.blade.php` file.

**Comment by poonasor** [comment]
in my test.blade.php file i have:
`<x-layout :SEOData="$SEOData">`

and still getting:
`Undefined variable $SEOData`

**Comment by ralphjsmit** [comment]
OK, that looks good, and how does your `layout.blade.php` look like?

**Comment by poonasor** [comment]
```
  @if (isset($SEOData))
    {!! seo($SEOData) !!}
  @else
    {!! seo() !!}
  @endif
```

**Comment by poonasor** [comment]
> So what was the issue?

its only pulling the default title and description, and won't pull the title and description from the controller

in my layout.blade.php i have:
```
        @if (isset($SEOData))
            {!! seo($SEOData) !!}
        @else
            {!! seo() !!}
        @endif
```

im getting:
`Undefined variable $SEOData`


in my controller:
`use RalphJSmit\Laravel\SEO\Support\SEOData;`
```
        return view('home', [
            'SEOData' => new SEOData(
                title: 'Awesome News - My Project',
                description: 'Lorem Ipsum',
            ),
        ]);
```
