### ISSUE TITLE
Escaping fields

### ISSUE THREAD

**Issue by AiAe** [ralphjsmit/laravel-seo#32]
Any specific reason why the library is not escaping fields? 

Since we are required to allow html from 
```
{!! seo()->for($SEOData) !!}
```

Then when I provide for example custom content like title/description and if it contains any HTML it will render it.

For example:
```
'SEOData' => new SEOData(
                title: 'Something</title><h1>test</h1><title></title>',
                description: '',
            ),
 ```

This will render the test on top of the page.

Sure i can solve the problem by adding `e('string')` everywhere but its a risk if someone forgets.

**Comment by ralphjsmit** [comment]
Hi! This was implemented some time ago already, I see I forgot to inform you here :)
