### ISSUE TITLE
Use in layout

### ISSUE THREAD

**Issue by ArtMin96** [ralphjsmit/laravel-seo#34]
If we have an `app.blade.php` layout, how do I pass the post to `->for()`?
```blade
{!! seo()->for($post) !!}
```

**Comment by ianclemence** [comment]
Hello, I'm currently facing a similar issue. How did you go about it?

**Comment by ralphjsmit** [comment]
Hello @ianclemence, what is the issue? In principle `{!! seo()->for($post) !}}` is the correct way.
