### ISSUE TITLE
Structured data for JobPosting

### ISSUE THREAD

**Issue by yamakrane** [ralphjsmit/laravel-seo#39]
Hello there,

Great job with the package. As mentioned by you, i come to you to know how to deal with job posting structured data as this is crucial for a lot of web apps who have a Hiring page and want to list that out on google jobs.

Thanks.

**Comment by QuentinGab** [comment]
#80 Would allow you to add a custom schema like the one you mentionned

**Comment by ralphjsmit** [comment]
Hi @yamakrane, you can now use the following to show the Job Posting: https://github.com/ralphjsmit/laravel-seo?tab=readme-ov-file#adding-your-first-schema. I likely won't be adding a fluent class for a JobPosting right now (but if you would like, I am open to PRs for custom fluent classes in addition to the ability you already have to export a custom JSON).
