### ISSUE TITLE
Description tag missing

### ISSUE THREAD

**Issue by JmzTaylor** [ralphjsmit/laravel-seo#41]
This is most likely a configuration issue on my end but I cannot figure it out.  The meta tags are showing up but description is missing.  Using the code below

model
```
public function getDynamicSEOData(): SEOData
    {
        return new SEOData(
            description: $this->excerpt,
        );
    }
```

blade
```
{!! seo($page ?? null) !!}
```

**Comment by guicRed** [comment]
Was having issues with this myself, seems like seo()->for($model) solved it for me.

If $page is your model then it should work with {!! seo()->for($page) !!}

**Comment by ralphjsmit** [comment]
Hey! Can do you update your code to `{!! dd(seo($page ?? null)) !!}` and send me the result?

**Comment by ralphjsmit** [comment]
Hi, closing this since I'm cleaning up some issues and I didn't receive a reply.
