### ISSUE TITLE
getDynamicSEOData : tags field

### ISSUE THREAD

**Issue by aeq-dev** [ralphjsmit/laravel-seo#45]
Hello,
I'm trying to add post tags (from spatie tags) but it's not rendered, 

```
 public function getDynamicSEOData(): SEOData
    {
        return new SEOData(
            title: $this->name,
            description: $this->short_description,
            author: app(GeneralSettings::class)->site_name,
            image: $this->getImageUrl(),
            tags: $this->getTags(),

        );
    }
```
`$this->getTags()` contains : 

```
[
  0 => "test"
  1 => "new"
  2 => "custom"
]
```
Theses tags doesn't appear in head meta, what's wrong ?

**Comment by ralphjsmit** [comment]
Have you included the following code in your Blade `<head>`?

```php
{!! seo()->for($postOrYourOtherModelName) !!}
```

**Comment by aeq-dev** [comment]
Yes of course, I mean just those tags ( `tags: $this->getTags(),)` don't appear, others tag such title, description, ... appear

**Comment by ralphjsmit** [comment]
@aeq-dev I looked into this and the `$SEOData->tags` property will be outputted into the OpenGraph `article:tag` property. The OpenGraph specification does not have an other tag reference (only `video:tag` and `article:tag`).

Therefore, the `article:tag` will only be outputted if the `$SEOData->type` is set to `article` ([code](https://github.com/ralphjsmit/laravel-seo/blob/6d8e36ca2e232ab8c35d6756887cc839efa6e701/src/Tags/OpenGraphTags.php#L65)). Therefore, the solution would be to update your `new SEOData()` class to include the `type: 'article'`.
