### ISSUE TITLE
How to keep Image URL parametres unchanged

### ISSUE THREAD

**Issue by zizu-kun** [ralphjsmit/laravel-seo#48]
I'm using Glide library to secure images and any change in the image URL, Glide take it as invalid.
is there a way to keep the URL without skipping parameters ?

example:

`https://website.test/images/xSVtl6ZF7fNuZIoXkZbzI2EzoAD.jpg?h=800&amp;fit=contain&amp;q=80&amp;fm=webp`

to be like this

`https://website.test/images/xSVtl6ZF7fNuZIoXkZbzI2EzoAD.jpg?h=800&fit=contain&q=80&fm=webp`

**Comment by ralphjsmit** [comment]
Hi @zizu-kun, I think the images were escaped by Blade, so I think your browser should be able to handle these correctly. But I just released version 1.6.2 that will prevent this escaping for only image URLs.
