### ISSUE TITLE
how to add custom meta?

### ISSUE THREAD

**Issue by jazzplunker97** [ralphjsmit/laravel-seo#52]
how to add custom meta?
i want to add meta keywords

**Comment by mohssineAboutaj** [comment]
You can do it like this
```
SEOManager::tagTransformer(function (TagCollection $tags): TagCollection {
  $tags = $tags->reject(fn (Tag $tag) => $tag instanceof OpenGraphTag);

  $tags->push(new MetaTag(name: 'keywords', content: 'laravel, php, web development, programming'));

  return $tags;
});
```
get more info from [here](https://github.com/ralphjsmit/laravel-seo#modifying-tags-before-they-are-rendered)

**Comment by ralphjsmit** [comment]
Yes, that's right! Hmm, must have missed this issue myself, but the solution from Mohssine is the right one 👍
