### ISSUE TITLE
meta name="twitter:image" displaying twice

### ISSUE THREAD

**Issue by qsinger** [ralphjsmit/laravel-seo#56]
The meta name="twitter:card" and meta name="twitter:image"  are displaying twice

**Comment by ralphjsmit** [comment]
Hmm, that's strange, I cannot replicate it. Do you have a screenshot of the `<head>`?

**Comment by qsinger** [comment]
![chrome_xuPDlzPZiM](https://github.com/ralphjsmit/laravel-seo/assets/38714918/959b4096-c5b3-4e2b-8c39-8406794422dd)

**Comment by ralphjsmit** [comment]
Hi @qsinger, I just looked into this and it has been fixed in version 1.6.1!
