### ISSUE TITLE
How to translate the url

### ISSUE THREAD

**Issue by ALSHIHAB** [ralphjsmit/laravel-seo#59]
I'm in the post page of 'en' version once I switch to 'ar' language the switch is successfull but the url still in english. 
This issue creates extra links for sitemap. 
I've used the package translate method in routes and links but doesn't work with dynamic post pages. So please tell how to make it. Thanks

**Comment by ralphjsmit** [comment]
Hmm, can you show some code? And the URL is the same for all languages? If yes, how do you store the current selected language (in session?)?

**Comment by ralphjsmit** [comment]
Hi, I'm closing this I'm cleaning up some issues and didn't receive a reply again.
