### ISSUE TITLE
Error SQLSTATE[42S22]: Column not found: 1054 Unknown column 'url' in 'field list' 

### ISSUE THREAD

**Issue by salmazz** [ralphjsmit/laravel-seo#60]
![3](https://github.com/ralphjsmit/laravel-seo/assets/16311634/55ab3312-a24e-4317-88ae-c2a06dd1b446)

when trying to update seo columns 
with this function             $model->seo->update($blogData['seo']);

Is it permissible for me to make an edit for these colmans?

**Comment by ralphjsmit** [comment]
Hi @salmazz! By default, the `seo` table contains a few columns. You can add more columns if you like using a migration!
