### ISSUE TITLE
Tags output order

### ISSUE THREAD

**Issue by skip405** [ralphjsmit/laravel-seo#66]
Hello. Thanks for this package :) Not really an issue, but is it possible to change the output order of the tags? Is there a way to specify it or sort tags before output?

**Comment by skip405** [comment]
Thanks for such a quick reply @ralphjsmit. I'll give it a try.

I've got a recommendation from my SEO specialist to output the `<title>` tag before the `<meta name="description" />`. But decided to ask a more generic question :)

**Comment by ralphjsmit** [comment]
Hey @skip405, I see, makes sense. Never heard about that recommendation before, but I'm open to a PR that changes the order in this file: https://github.com/ralphjsmit/laravel-seo/blob/main/src/TagCollection.php. Then I assume that the output order will also be updated.

**Comment by skip405** [comment]
Yep, it seems to match the output order I'm seeing on the page. Thanks for pointing me in the right direction. I'll think about a PR :wink:

**Comment by ralphjsmit** [comment]
Great 👍
