### ISSUE TITLE
How to add Video Structure Schema?

### ISSUE THREAD

**Issue by ronald2wing** [ralphjsmit/laravel-seo#69]
I want to add the video data to the page. How do I do that?

**Comment by ralphjsmit** [comment]
Using OpenGraph? You can push an OpenGraph tag.

**Comment by ronald2wing** [comment]
https://www.semrush.com/blog/video-schema/

It may be outside the scope of this package. I want to ask before searching for other solutions.

**Comment by QuentinGab** [comment]
#81 Would allow you to define a video schema

**Comment by ronald2wing** [comment]
@QuentinGab Many thanks you!

**Comment by ralphjsmit** [comment]
Hi @ronald2wing, the PR from #81 has just been released in 1.6.0, you can now use the following to define the Video schema: https://github.com/ralphjsmit/laravel-seo?tab=readme-ov-file#adding-your-first-schema.

**Comment by ronald2wing** [comment]
Thank you for a great job!
