### ISSUE TITLE
Compatible with Laravel Nova

### ISSUE THREAD

**Issue by yasinkocak** [ralphjsmit/laravel-seo#7]
Is there a example to use this with Laravel Nova?

**Comment by ralphjsmit** [comment]
I don't have experience with Nova, but it looks like you can use the following syntax:

```php
MorphOne::make('seo')->fields([
    Text::make('title'),
     // ..
]);
```

With something like this, you should certainly be able to get it working.

**Comment by ralphjsmit** [comment]
Closing this for now since I didn't hear anymore from you. Feel to comment if there's still a question!
