### ISSUE TITLE
Not showing my seo from model, but from defaults

### ISSUE THREAD

**Issue by ADezon** [ralphjsmit/laravel-seo#76]
I'm sorry to bother you, I've read the docs again and again... but I can't get  {!! (seo($page ?? null)) !!} to show the SEO stored by the seo model...
Is there something I'm missing?

Dumping the seo call at blade {!! dd(seo($page ?? null)) !!}, I get this:
```
RalphJSmit\Laravel\SEO\TagManager {#2555 ▼ // resources/views/layouts/app.blade.php
  +model: ? Illuminate\Database\Eloquent\Model
  +SEOData: ? RalphJSmit\Laravel\SEO\Support\SEOData
  +tags: 
RalphJSmit\Laravel\SEO
\
TagCollection {#2036 ▼
    #items: array:6 [▶]
    #escapeWhenCastingToString: false
  }
}
```
with results in defaults for seo:
![image](https://github.com/ralphjsmit/laravel-seo/assets/22474668/885b8a76-60d3-49e0-9f9f-2515da976b1b)

BUT in my controller (PostController) I check the SEO for my post:

        $seo = $post->seo;
        dump($seo->toArray());

I get the correct data:
```
array:11 [▼ // app/Http/Controllers/PostController.php:15
  "id" => 1
  "model_type" => "App\Models\Post"
  "model_id" => 1
  "description" => "The best description is one that incites the imagination."
  "title" => "Manually set SEO Title at creation/update (test)!!"
  "image" => null
  "author" => "Cyrus Frank"
  "robots" => null
  "canonical_url" => null
  "created_at" => "2024-05-04T08:57:57.000000Z"
  "updated_at" => "2024-05-04T09:50:39.000000Z"
]
```

How can I get {!! seo() !!} to use the current stored seo data of my post?
Thanks a lot (in advance) :)

**Comment by ralphjsmit** [comment]
Hi @ADezon! It seems like the variable `$page ?? null` is undefined, and then it falls back to null using the `?? null`. 
Could it be that you need to use the variable `$post` perhaps?

Can you try to `dd($page)` and `dd($post)`?

**Comment by ADezon** [comment]
OMG!! you are right!! 
And of course it works!!
And I feel so dummy!!
Thanks 4 replying this 🤦🏻‍♂️!

I'm using filment extension too!
Great work!!
