### ISSUE TITLE
Proposal: Refactoring `SchemaCollection` to allow any schema to be added

### ISSUE THREAD

**Issue by QuentinGab** [ralphjsmit/laravel-seo#80]
Hi @ralphjsmit,

I've been exploring your package a lot lately, and as you saw in my previous PR, I'm willing put some work together to make it perfect.

I'm facing some limitations regarding the definition of JSON schemas and previous issues also put light on the need for a more flexible architecture.

I'm proposing to refactor `SchemaCollection` without breaking changes, to make it accept any schema type. 

Actually I think that this package should not try to implement any Schema specifically like it was done for `ArticleSchema` and `BreadcrumbListSchema`. Json Schemas definitions are really vast as you mention in the doc, it would be a nightmare to maintain any class implementation.

## What do I suggest ?

Instead of relying on class, SchemaCollection could just rely on function and array.

```php
SchemaCollection::make()
  ->add(function(SEOData $seoData){
    return [
      '@type' => 'Article',
      'headline' => $seoData->title
    ];
  })
  ->add([
    '@type' => 'BreadcrumbList',
    // ...
  ])
```
You could have predefined function

In my opinion, this is the best way to allow users to add any schema they want while still providing some suggestions for the most relevant ones.

Does it sound good to you ? If you are willing to try it, I can put a PR together asap

**Comment by ralphjsmit** [comment]
Hi Quentin, thank you, I agree that giving the users at least the option to add custom schemas themselves would be great and give much more versatility. 

To confirm, the SchemaCollection ->add() function would be called globally, and then receive a SEOData object for every page on the site? If so, the perhaps some functionality is also needed in order to determine when a schema should not be outputted (perhaps return an empty array or sth) I think?

**Comment by ralphjsmit** [comment]
If you could PR the (WIP) code you have that would be great. Then I'll look at it and release it as one version together with the other two PRs 👌

**Comment by QuentinGab** [comment]
All right, I'm gonna do it today

**Comment by QuentinGab** [comment]
#81 I just made the PR so I'm closing this issue
