### ISSUE TITLE
AlternateTag class is missing

### ISSUE THREAD

**Issue by VisionovaDev** [ralphjsmit/laravel-seo#82]
I don't find AlternateTag class in the source of the package so it is not possible to run this code: (extracted from README)
public function getDynamicSEOData(): SEOData
{
    return new SEOData(
        title: $this->title,
        description: $this->excerpt,
        author: $this->author->fullName,
        alternates: [
            new AlternateTag(
                hreflang: 'en',
                href: "https://example.com/en",
            ),
            new AlternateTag(
                hreflang: 'fr',
                href: "https://example.com/fr",
            ),
        ],
    );
}

**Comment by QuentinGab** [comment]
Hi @VisionovaDev,

AlternateTag is not released yet, I suppose it will be released in the coming days

**Comment by ralphjsmit** [comment]
Hi @VisionovaDev, it wasn't released since we wanted to combine it with an other PR that was open. I just reviewed and finished that PR today and released all the outstanding features in version 1.6.0, including the `AlternateTag` support. 

Let me know if this works for you!

**Comment by VisionovaDev** [comment]
Hi @ralphjsmit
It works !
Thank you for your efforts.

**Comment by ralphjsmit** [comment]
Mainly thanks to Quentin for providing the original idea and PR :)
