### ISSUE TITLE
500 When Calling Model::shouldBeStrict() in AppServiceProvider

### ISSUE THREAD

**Issue by falconsmilie** [ralphjsmit/laravel-seo#86]
Hi.

When i have this code;

```

class AppServiceProvider extends ServiceProvider
{
    ....

    public function boot(): void
    {
        // All-in-one for preventLazyLoading, preventAccessingMissingAttributes and preventSilentlyDiscardingAttributes
        Model::shouldBeStrict(!app()->isProduction());

        ...
    }
}

```

It results in a 500;

`The attribute [canonical_url] either does not exist or was not retrieved for model [RalphJSmit\Laravel\SEO\Models\SEO].`

The "easy" fix is to add the members of `\RalphJSmit\Laravel\SEO\Support\SEOData` to the `\RalphJSmit\Laravel\SEO\Models\SEO` class, but i'm not sure if this is the right direction to take.

**Comment by ralphjsmit** [comment]
Hi @falconsmilie , thank you for your report! Could you perhaps share the full Flare link to the error you are getting? Then I can look where it originates from and resolve it. Does it originate from [here](https://github.com/ralphjsmit/laravel-seo/blob/e2fb6350d2e648fd8f88011e1d730d8f9633032b/src/Models/SEO.php#L49)?

**Comment by falconsmilie** [comment]
Hi @ralphjsmit , you're linking to the correct line of code.

https://flareapp.io/share/o7A2eZd5

When you expand the vendor frames, it is the 4th one.

**Comment by ralphjsmit** [comment]
Hi @falconsmilie, thanks! Fixed in https://github.com/ralphjsmit/laravel-seo/releases/tag/1.6.3.
